api_root_path: /
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
docs_url: /docs
host: 127.0.0.1
kafka_servers:
- kafka:9092
log_level: info
openapi_url: /openapi.json
port: 8080
private_key: dummy-key
publisher_topic: file_interrogation
publisher_type: file_validation_success
service_instance_id: '1'
service_name: fis
source_bucket_id: test-staging
token_hashes:
- abcdef
- ghijkl
vault_path: ekss
vault_role_id: '**********'
vault_secret_id: '**********'
vault_url: http://127.0.0.1:8200
vault_verify: true
workers: 1
