api_root_path: /
api_route: /ga4gh/drs/v1
auto_reload: true
aws_config_ini: null
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
custom_spec_url: null
db_print_logs: false
db_url: postgresql://admin:admin@postgresql/storage
docs_url: /docs
drs_self_url: drs://localhost:8080/
host: 127.0.0.1
log_level: info
openapi_url: /openapi.json
port: 8080
rabbitmq_host: rabbitmq
rabbitmq_port: 5672
s3_access_key_id: test
s3_endpoint_url: http://drs3:4566
s3_outbox_bucket_id: outbox
s3_secret_access_key: test
s3_session_token: null
service_name: drs3
topic_name_drs_object_registered: drs-object-registered
topic_name_file_registered: file-internally-registered
topic_name_file_staged: file_staged_for_download
topic_name_stage_request: non_staged_file_requested
workers: 1
