api_root_path: ''
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
db_connection_str: '**********'
db_name: dev
docs_url: /docs
file_upload_validation_success_topic: file-upload-validation-success
file_validations_collection: fileValidations
generate_correlation_id: true
host: 127.0.0.1
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
log_traceback: true
openapi_url: /openapi.json
port: 8080
private_key: dummy-key
service_account_token_path: /var/run/secrets/kubernetes.io/serviceaccount/token
service_instance_id: '1'
service_name: fis
source_bucket_id: staging
token_hashes:
- abcdef
- ghijkl
vault_auth_mount_point: null
vault_kube_role: dummy-role
vault_path: ekss
vault_role_id: '**********'
vault_secret_id: '**********'
vault_secrets_mount_point: secret
vault_url: http://127.0.0.1:8200
vault_verify: true
workers: 1
