api_root_path: ''
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
cors_exposed_headers: null
db_name: dev
db_version_collection: fisDbVersions
docs_url: /docs
enable_opentelemetry: false
file_interrogations_topic: file-interrogations
file_validations_collection: fileValidations
generate_correlation_id: true
host: 127.0.0.1
interrogation_failure_type: interrogation_failed
interrogation_success_type: interrogation_success
kafka_compression_type: null
kafka_dlq_topic: dlq
kafka_enable_dlq: false
kafka_max_message_size: 1048576
kafka_max_retries: 0
kafka_retry_backoff: 0
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
log_traceback: true
migration_max_wait_sec: null
migration_wait_sec: 10
mongo_dsn: '**********'
mongo_timeout: null
openapi_url: /openapi.json
otel_trace_sampling_rate: 1.0
port: 8080
private_key_passphrase: null
private_key_path: placeholder.sec
service_account_token_path: /var/run/secrets/kubernetes.io/serviceaccount/token
service_instance_id: '1'
service_name: fis
token_hashes:
- abcdef
- ghijkl
vault_auth_mount_point: null
vault_kube_role: dummy-role
vault_path: ekss
vault_role_id: '**********'
vault_secret_id: '**********'
vault_secrets_mount_point: secret
vault_url: http://127.0.0.1:8200
vault_verify: true
workers: 1
