# Please only mention the non-default settings here:

vault_url: "http://127.0.0.1:8200"
vault_role_id: dummy-role
vault_secret_id: dummy-secret
vault_verify: True
server_private_key: 9iYLar4OyeBzKJY8xQ8BAiGUe49wmqRPtcj240+VmjQ=
server_public_key: HsKvfHsAFNGykFi/zMssay0xajoHvY30IcYPGDCXrGU=
