[project]
name = "dcs"
version = "1.1.0"
description = "Download Controller Service - a GA4GH DRS-compliant service for delivering files from S3 encrypted according to the GA4GH Crypt4GH standard."
dependencies = [
    "typer >= 0.9.0",
    "ghga-service-commons[api] >= 2.0.0",
    "ghga-event-schemas >= 1.0.0",
    "hexkit[akafka,s3,mongodb] >= 2.0.0"
]

[project.urls]
Repository = "https://github.com/ghga-de/dcs"

[project.scripts]
dcs = "dcs.__main__:cli"
