[project]
name = "ekss"
version = "1.1.0"
description = "Encryption Key Store Sevice - providing crypt4gh file secret extraction, storage and envelope generation"
dependencies = [
    "ghga-service-commons[all]>=2.0.0",
    "hexkit>=2.0.0",
    "typer>=0.9.0",
    "crypt4gh>=1.6",
    "hvac>=2",
]

[project.urls]
Repository = "https://github.com/ghga-de/encryption-key-store-service"

[project.scripts]
ekss = "ekss.__main__:run"
